version: '3.9'


services:
  app:
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
      - ./db:/wd/db:rw

    user: "1000"
    ports:
      - '8000:8000'
    command:
      - --host=0.0.0.0


