version: '3.9'


services:
  app:
    ports:
        - '5000:5000'
    command:
        - --host=0.0.0.0
    volumes:
      - ./files_input:/wd/files_input:rw
      - ./files_output:/wd/files_output:rw
      - ./db:/wd/db:rw





